import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'

const urlImage = 'https://image.tmdb.org/t/p/original';
export default function MovieItem({info}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{info.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {info.title}
        </h1>
        <p>Nota: {info.vote_average}</p>
        <p>Descrição: {info.overview}</p>
        <img src={`${urlImage}/${info.backdrop_path}`} alt="Poster do filme" width="720" /> <br/>
        <Link href="/">Menu principal</Link>
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
    const res = await fetch(`http://localhost:3000/api/movie/${context.params.id}`);
    const json = await res.json();

    return {
        props: {
            info: json.list
        }
    }
}