import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

const urlImage = 'https://image.tmdb.org/t/p/original';

export default function Busca({list}) {
    const [searchText, setSearchText] = useState('');
    const [movieList, setMovieList] = useState([]);

    const handleSearch = async () => {
        if(searchText !== ''){
            const result = await fetch(`http://localhost:3000/api/search?q=${searchText}`);
            const json = await result.json();
            setMovieList(json.list);
        }
    }
  return (
    <div className={styles.container}>
      <Head>
        <title>Busca de produtos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Busca
        </h1>

        <input type="text" value={searchText} onChange={e => setSearchText(e.target.value)} /> <br/>
        <button onClick={handleSearch}>Buscar</button>

        <hr />
        <ul>
            {movieList.map(item => (
                <li>
                    <a href={`/movie/${item.id}`}>
                        <img src={`${urlImage}${item.poster_path}`} alt="Imagem do filme" width="150" /> <br/>
                        {item.title}
                    </a>
                </li>
            ))}
        </ul>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/trending');
  const json = await res.json();
  return {
    props: {
      list: json.list
    }
  }
}