import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const urlImage = 'https://image.tmdb.org/t/p/original';
export default function Home({list}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Filmes em destaque</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Filmes em destaque
        </h1>

        <Link href="/busca">Ir para a busca</Link>

        <ul>
          {list.map(item => (
            <li>
              <a href={`/movie/${item.id}`}>
                <img src={`${urlImage}${item.poster_path}`} alt="Imagem do filme" width="150" /> <br/>
                {item.title}
              </a>
            </li>
          ))}
        </ul>
        <Link href="/sobre">Sobre</Link>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/trending');
  const json = await res.json();
  return {
    props: {
      list: json.list
    }
  }
}