import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const urlImage = 'https://image.tmdb.org/t/p/original';
export default function About({author}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sobre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sobre
        </h1>
        <p>O sistema foi feito em live para demonstrar os primeiros passos com o framework Next.JS</p>
        <hr/>
        Autora: {author} <br />
        <Link href="/">Home</Link>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {
      author: 'Isabela'
    }
  }
}